-- ═══════════════════════════════════════════════════════════════════════════════
-- AI SAMAJH - Supabase PostgreSQL Database Schema
-- 5 Tables for AI News Platform with Personalization
-- ═══════════════════════════════════════════════════════════════════════════════

-- ───────────────────────────────────────────────────────────────────────────────
-- TABLE 1: user_profiles
-- Stores user information and preferences for personalized news delivery
-- Each user has a role that determines how AI news is contextualized for them
-- ───────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS user_profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email TEXT UNIQUE NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('student', 'professional', 'business', 'investor', 'citizen')),
    goal TEXT,                                    -- User's primary goal (e.g., "learn AI for career")
    language TEXT DEFAULT 'english',              -- Preferred language for content
    industry TEXT,                                -- User's industry (for relevance scoring)
    ai_score INTEGER DEFAULT 0 CHECK (ai_score >= 0 AND ai_score <= 100),  -- AI literacy score (0-100)
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ───────────────────────────────────────────────────────────────────────────────
-- TABLE 2: articles
-- Stores scraped AI news articles with ELI5 explanations and metadata
-- Each article is processed by our AI agents to generate context
-- ───────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS articles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    url TEXT UNIQUE NOT NULL,                     -- Original article URL (unique to prevent duplicates)
    source TEXT,                                  -- Source website (e.g., "TechCrunch", "OpenAI Blog")
    category TEXT CHECK (category IN ('research', 'product', 'funding', 'regulation', 'opinion')),
    original_text TEXT,                           -- Full article content
    eli5 TEXT,                                    -- "Explain Like I'm 5" summary with Indian context
    credibility INTEGER DEFAULT 50,               -- Credibility score (0-100)
    published_at TIMESTAMPTZ,                     -- Original publication date
    processed_at TIMESTAMPTZ DEFAULT NOW(),       -- When our pipeline processed it
    relevance_scores JSONB DEFAULT '{}'::jsonb    -- Relevance scores per role: {"student": 85, "professional": 70, ...}
);

-- ───────────────────────────────────────────────────────────────────────────────
-- TABLE 3: article_contexts
-- Stores personalized "why it matters" and action items for each user role
-- Each article has 5 contexts (one per role) generated by Gemini
-- ───────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS article_contexts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    article_id UUID REFERENCES articles(id) ON DELETE CASCADE,
    user_role TEXT NOT NULL,                      -- Target role: student, professional, business, investor, citizen
    why_it_matters TEXT,                          -- Personalized explanation of article's relevance
    action_items JSONB DEFAULT '[]'::jsonb,       -- Array of actionable items: [{"label": "Try It", "url": "...", ...}]
    language TEXT DEFAULT 'english',              -- Language of this context
    localized_eli5 TEXT                           -- Translated ELI5 for non-English users
);

-- ───────────────────────────────────────────────────────────────────────────────
-- TABLE 4: user_interactions
-- Tracks user engagement with articles for analytics and recommendations
-- Used to improve personalization over time
-- ───────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS user_interactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES user_profiles(id) ON DELETE CASCADE,
    article_id UUID REFERENCES articles(id) ON DELETE CASCADE,
    action_type TEXT CHECK (action_type IN ('read', 'action_click', 'share', 'bookmark')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ───────────────────────────────────────────────────────────────────────────────
-- TABLE 5: chat_history
-- Stores AI tutor conversation history for each user
-- Enables contextual follow-up questions and learning continuity
-- ───────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS chat_history (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES user_profiles(id) ON DELETE CASCADE,
    role TEXT CHECK (role IN ('user', 'assistant')),  -- Message sender
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ═══════════════════════════════════════════════════════════════════════════════
-- INDEXES - For optimized query performance
-- ═══════════════════════════════════════════════════════════════════════════════

-- Fast filtering by article category
CREATE INDEX idx_articles_category ON articles(category);

-- Fast sorting by publication date (newest first)
CREATE INDEX idx_articles_published ON articles(published_at DESC);

-- Fast lookup of contexts by article and role
CREATE INDEX idx_article_contexts_lookup ON article_contexts(article_id, user_role);

-- Fast retrieval of user's interaction history
CREATE INDEX idx_interactions_user ON user_interactions(user_id, created_at DESC);

-- Fast retrieval of user's chat history
CREATE INDEX idx_chat_user ON chat_history(user_id, created_at);

-- ═══════════════════════════════════════════════════════════════════════════════
-- ENABLE ROW LEVEL SECURITY (RLS) - Optional but recommended for production
-- ═══════════════════════════════════════════════════════════════════════════════

-- Enable RLS on all tables
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE article_contexts ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_interactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_history ENABLE ROW LEVEL SECURITY;

-- Policy: Users can read all articles (public)
CREATE POLICY "Articles are viewable by everyone" ON articles
    FOR SELECT USING (true);

-- Policy: Article contexts are viewable by everyone
CREATE POLICY "Article contexts are viewable by everyone" ON article_contexts
    FOR SELECT USING (true);

-- Policy: Users can only see their own profile
CREATE POLICY "Users can view own profile" ON user_profiles
    FOR SELECT USING (auth.uid()::text = id::text OR auth.role() = 'service_role');

-- Policy: Users can insert their own profile
CREATE POLICY "Users can insert own profile" ON user_profiles
    FOR INSERT WITH CHECK (true);

-- Policy: Users can update their own profile
CREATE POLICY "Users can update own profile" ON user_profiles
    FOR UPDATE USING (auth.uid()::text = id::text OR auth.role() = 'service_role');

-- Policy: Users can see their own interactions
CREATE POLICY "Users can view own interactions" ON user_interactions
    FOR SELECT USING (auth.uid()::text = user_id::text OR auth.role() = 'service_role');

-- Policy: Users can insert their own interactions
CREATE POLICY "Users can insert own interactions" ON user_interactions
    FOR INSERT WITH CHECK (true);

-- Policy: Users can see their own chat history
CREATE POLICY "Users can view own chat history" ON chat_history
    FOR SELECT USING (auth.uid()::text = user_id::text OR auth.role() = 'service_role');

-- Policy: Users can insert their own chat messages
CREATE POLICY "Users can insert own chat messages" ON chat_history
    FOR INSERT WITH CHECK (true);

-- ═══════════════════════════════════════════════════════════════════════════════
-- GRANT SERVICE ROLE FULL ACCESS (for backend Python agents)
-- ═══════════════════════════════════════════════════════════════════════════════

-- Service role can do everything (used by Python backend)
CREATE POLICY "Service role has full access to articles" ON articles
    FOR ALL USING (auth.role() = 'service_role');

CREATE POLICY "Service role has full access to article_contexts" ON article_contexts
    FOR ALL USING (auth.role() = 'service_role');

CREATE POLICY "Service role has full access to user_profiles" ON user_profiles
    FOR ALL USING (auth.role() = 'service_role');

CREATE POLICY "Service role has full access to user_interactions" ON user_interactions
    FOR ALL USING (auth.role() = 'service_role');

CREATE POLICY "Service role has full access to chat_history" ON chat_history
    FOR ALL USING (auth.role() = 'service_role');
